// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe15qqv6ajQhfTHL49tDTI2gq1kUxivyg',
    appId: '1:431272703845:web:c5cfd41c2659a767b1138c',
    messagingSenderId: '431272703845',
    projectId: 'visco-156c5',
    authDomain: 'visco-156c5.firebaseapp.com',
    storageBucket: 'visco-156c5.appspot.com',
    measurementId: 'G-CSKEJE72QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB07zDZLUN-9wjBv2g6iGwfQ77YqzznzMU',
    appId: '1:431272703845:android:5a7a6c9172bbafa0b1138c',
    messagingSenderId: '431272703845',
    projectId: 'visco-156c5',
    storageBucket: 'visco-156c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuB4XXmX3zW01FtYTXGItnvaMu3GicMx8',
    appId: '1:431272703845:ios:2a54b5a1e57d3c63b1138c',
    messagingSenderId: '431272703845',
    projectId: 'visco-156c5',
    storageBucket: 'visco-156c5.appspot.com',
    iosClientId: '431272703845-1qpfe1pbb6s8a7ap8ikcjg3jrhlqnmml.apps.googleusercontent.com',
    iosBundleId: 'com.example.visco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuB4XXmX3zW01FtYTXGItnvaMu3GicMx8',
    appId: '1:431272703845:ios:2a54b5a1e57d3c63b1138c',
    messagingSenderId: '431272703845',
    projectId: 'visco-156c5',
    storageBucket: 'visco-156c5.appspot.com',
    iosClientId: '431272703845-1qpfe1pbb6s8a7ap8ikcjg3jrhlqnmml.apps.googleusercontent.com',
    iosBundleId: 'com.example.visco',
  );
}
